spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:mysql://localhost:3306/my_note?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    #url: jdbc:p6spy:mysql://localhost:3306/my_note?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 962789love

  mail:
    host: smtp.qq.com
    username: 470402780@qq.com
    password: vdwynyhqbjmtbgbi
    default-encoding: UTF-8

server:
  port: 8123


logging:
  level:
    org.zzr.mynote.mapper: debug
  pattern:
    console: '%p%m%n'

mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1


nginx:
  # nginx 文件目录
  #path: /Users/yangkaile/Projects/nginx/keller/
  path: D:\\workapp\\mynote-repository\\
  # nginx 服务器访问地址
  url: http://localhost:8081/keller/
  # 原图存放的相对目录

img:
  # 原图存放的相对目录
  path: image\\img\\


thum:
  # 缩略图存放的相对目录
  path: image\\thum\\

# 前端访问地址
web:
    url: http://127.0.0.1:8080
